import { useState } from 'react'
import { withAttempt } from '../../../lib/imageRetry'

// ---------------------------------------------------------------------------
// Generated creatives, and the one honest thing a grid of AI images must do:
// survive an image that does not load.
//
// The image endpoints hand back URLs on third-party hosts. Those hosts
// rate-limit, time out, and occasionally return an error page with a 200. A
// plain <img> grid answers all of that with a broken-image icon and no
// explanation, so each tile tracks its own load state and says what happened.
//
// Selection is local to the grid: the chosen tile is what the rail's Download
// acts on, so a user comparing four versions downloads the one they are
// looking at rather than the first one generated.
// ---------------------------------------------------------------------------

/**
 * Was this image generated, or substituted?
 *
 * The image chain falls back to a keyword-matched stock photo when the AI host
 * rate-limits or errors. That photo is perfectly usable — but it is not a
 * generated creative, and the difference has to be visible or the user comes to
 * believe generation is working when it is not.
 */
function sourceBadge(source) {
  if (!source) return null
  if (source.startsWith('pollinations')) return null // generated — the norm, no badge
  if (source === 'loremflickr') return 'Stock photo'
  if (source === 'picsum') return 'Placeholder'
  return source
}

/**
 * How many of these versions were not generated by the model.
 *
 * BUG-06: a three-version request came back as one AI image and two random
 * photographs, and the only signal was a small amber badge on two tiles — easy
 * to miss, and it says nothing about the proportion. A one-line summary above
 * the grid states the count, so the delivered default is never mistaken for
 * three generated creatives.
 */
export function substitutionSummary(sources = []) {
  const total = sources.length
  if (!total) return null

  // An unlabelled source is not known to be generated, so it is counted as a
  // substitution: assuming the best about an image we cannot identify is how a
  // stock photo ends up presented as a generated creative.
  const substituted = sources.filter((s) => !s || !s.startsWith('pollinations')).length
  if (!substituted) return null

  const generated = total - substituted
  return (
    `${substituted} of ${total} version${total === 1 ? '' : 's'} fell back to stock ` +
    `photography because the image host was rate-limiting. ` +
    (generated
      ? `${generated} ${generated === 1 ? 'is' : 'are'} AI-generated.`
      : 'None of these are AI-generated.')
  )
}

/**
 * A tile that failed to load, with a way to try again.
 *
 * BUG-10: a failed tile read "This one didn't load — the image host may be
 * rate-limiting. Generate again." and offered nothing to click. The advice was
 * right and the affordance was missing, so the only option was to re-run the
 * whole generation and pay for every other version again.
 *
 * Retrying re-fetches *this* image rather than asking the model for a new one.
 * That is the honest reading of "the image host may be rate-limiting": the URL
 * is good and the host was busy, so the thing to wait out is seconds, not a new
 * generation. It also keeps the selection stable, which re-generating would not.
 *
 * A rate limit is typically counted per URL, so a plain retry of the same URL can
 * return the same cached error. The `attempt` is appended as a cache-busting
 * query for exactly that reason.
 */
function Tile({ src, label, source, selected, onSelect }) {
  const [state, setState] = useState('loading')
  const [attempt, setAttempt] = useState(0)
  const badge = sourceBadge(source)

  // The URL that is actually loaded. `attempt` is what changes on a retry.
  const loaded = attempt === 0 ? src : withAttempt(src, attempt)

  function retry(event) {
    // The tile is a button, so a click on this would also select the tile.
    event.stopPropagation()
    setState('loading')
    setAttempt((n) => n + 1)
  }

  return (
    <button
      type="button"
      onClick={() => onSelect?.(src)}
      className={`group relative block overflow-hidden rounded-xl border-2 text-left transition ${
        selected ? 'border-accent' : 'border-line hover:border-accent-line'
      }`}
    >
      <div className="relative aspect-square w-full bg-inset">
        {state !== 'error' && (
          <img
            key={loaded}
            src={loaded}
            alt={label || 'Generated creative'}
            loading="lazy"
            onLoad={() => setState('ok')}
            onError={() => setState('error')}
            className={`h-full w-full object-cover transition-opacity ${
              state === 'ok' ? 'opacity-100' : 'opacity-0'
            }`}
          />
        )}

        {state === 'loading' && (
          <div className="absolute inset-0 grid place-items-center">
            <span className="skeleton h-full w-full" />
          </div>
        )}

        {badge && state !== 'error' && (
          <span className="absolute left-2 top-2 rounded-md bg-amber-500/90 px-1.5 py-1 text-[10px] font-bold text-white shadow-sm">
            {badge}
          </span>
        )}

        {state === 'error' && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 p-3 text-center">
            <span className="text-xs leading-relaxed text-muted">
              This one didn&apos;t load — the image host may be rate-limiting.
            </span>
            <span
              role="button"
              tabIndex={0}
              onClick={retry}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  retry(e)
                }
              }}
              className="rounded-md border border-line bg-surface px-2.5 py-1 text-xs font-semibold text-body hover:border-accent-line focus:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            >
              Retry
            </span>
          </div>
        )}
      </div>

      {label && (
        <span className="block truncate border-t border-line px-2.5 py-1.5 text-[11px] font-medium text-body">
          {label}
        </span>
      )}
    </button>
  )
}

export default function CreativeResults({
  images,
  labels = [],
  sources = [],
  selected,
  onSelect,
  columns = 2,
}) {
  if (!images?.length) return null

  const summary = substitutionSummary(sources)

  return (
    <div className="space-y-2">
      {summary && (
        <p className="rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs leading-relaxed text-amber-700">
          {summary}
        </p>
      )}

      <div
        className={`grid gap-3 ${columns === 3 ? 'sm:grid-cols-3' : 'sm:grid-cols-2'}`}
      >
        {images.map((src, i) => (
          <Tile
            key={`${src}-${i}`}
            src={src}
            label={labels[i]}
            source={sources[i]}
            selected={selected === src}
            onSelect={onSelect}
          />
        ))}
      </div>
    </div>
  )
}
