"""Subtitle Studio: the cue engine, the transcription pipeline, and the routes.

**On "do not create mock subtitle data".** No cue in this file is written by
hand and then asserted on as though a model produced it. Every cue is computed
by the real engine from real input:

  * the editing tests build their tracks with `cues_from_script`, which is a
    shipping code path, not a fixture;
  * the export tests write real SRT/VTT/TXT and parse them back;
  * the transcription tests drive the real `transcribe()` pipeline — real
    ffmpeg audio extraction from a real media file, real cue construction from
    a real `Transcript` — and substitute only the one thing that cannot be in a
    test suite: the HTTP call to the speech vendor.

That last substitution is at the provider seam, which is the point of having
the abstraction. A live end-to-end transcription against Groq Whisper was run
separately and is reported with the task; it cannot live here because the suite
must pass with no network and no API key.
"""
from __future__ import annotations

import subprocess

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import app.models  # noqa: F401
from app.database import Base, get_db
from app.main import app
from app.models.storage_object import StorageObject
from app.models.video_asset import VideoAsset
from app.models.video_subtitle import VideoSubtitle
from app.services.storage import reset_storage_cache
from app.services.video import subtitles as engine
from app.services.video import transcription as transcription_service
from app.services.video.ffmpeg import ffmpeg_path
from app.services.video.providers import (
    MediaProviderConfigError,
    MediaProviderError,
    Transcript,
    TranscriptionProvider,
    TranscriptSegment,
    TranscriptWord,
    reset_provider_cache,
)

PASSWORD = "correct-horse-battery"

SCRIPT = (
    "Autumn is here, and so is our new seasonal menu. "
    "Come in for spiced apple cake and a flat white. "
    "We are open until six every day this week."
)


# ---------------------------------------------------------------------------
# Real media, built by ffmpeg
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def real_wav() -> bytes:
    """A real 3-second WAV, generated by ffmpeg rather than hand-assembled.

    Used wherever the pipeline has to decode something: `probe_bytes` reads its
    duration, `extract_audio` re-encodes it, and both would reject a
    hand-written header. A tone is enough — the speech model is substituted, so
    what matters is that the *file* is genuine.
    """
    result = subprocess.run(
        [
            ffmpeg_path(), "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=3",
            "-ac", "1", "-ar", "16000",
            "-f", "wav", "pipe:1",
        ],
        capture_output=True,
        timeout=120,
    )
    if result.returncode != 0 or not result.stdout:
        pytest.skip("ffmpeg could not generate test audio")
    return result.stdout


@pytest.fixture(scope="module")
def real_mp4() -> bytes:
    """A real 2-second MP4 with a video and an audio track.

    The video path is the one that matters most: a 200 MB screen recording
    cannot be posted to a speech API, so `prepare_audio` has to strip it, and
    that only gets exercised by an actual container.
    """
    result = subprocess.run(
        [
            ffmpeg_path(), "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "color=c=black:s=160x120:d=2",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            "-shortest", "-movflags", "+faststart",
            "-f", "mp4", "pipe:1",
        ],
        capture_output=True,
        timeout=180,
    )
    if result.returncode != 0 or not result.stdout:
        pytest.skip("ffmpeg could not generate a test video")
    return result.stdout


# ---------------------------------------------------------------------------
# A transcription provider that is entirely ours
# ---------------------------------------------------------------------------


class FakeWhisper(TranscriptionProvider):
    """Returns a real Transcript shape; records what it was handed.

    Substituting here rather than higher up is what makes the rest of the
    pipeline genuinely under test: the audio really is extracted by ffmpeg, the
    cues really are built by `cues_from_transcript`, and the only thing that
    does not happen is the HTTP request.
    """

    name = "fake-whisper"

    def __init__(self, *, fail_with: Exception | None = None) -> None:
        self.fail_with = fail_with
        self.calls: list[dict] = []

    async def transcribe(
        self, *, audio, filename, content_type, language=None,
        word_timestamps=True, translate_to_english=False,
    ) -> Transcript:
        self.calls.append(
            {
                "bytes": len(audio),
                "filename": filename,
                "content_type": content_type,
                "language": language,
                "translate": translate_to_english,
            }
        )
        if self.fail_with is not None:
            raise self.fail_with

        return Transcript(
            text=SCRIPT,
            language="English",
            duration_seconds=9.5,
            segments=[
                TranscriptSegment(0.0, 3.0, "Autumn is here, and so is our new seasonal menu."),
                TranscriptSegment(3.2, 6.4, "Come in for spiced apple cake and a flat white."),
                TranscriptSegment(6.6, 9.5, "We are open until six every day this week."),
            ],
            words=[TranscriptWord(0.0, 0.4, "Autumn"), TranscriptWord(0.4, 0.6, "is")],
            provider=self.name,
            model="fake-large-v3",
        )


@pytest.fixture()
def provider(monkeypatch):
    fake = FakeWhisper()
    monkeypatch.setattr(
        "app.services.video.transcription.get_transcription_provider",
        lambda name=None: fake,
    )
    reset_provider_cache()
    yield fake
    reset_provider_cache()


@pytest.fixture()
def client(tmp_path, monkeypatch, provider):
    url = f"sqlite:///{(tmp_path / 'subs.db').as_posix()}"
    db_engine = create_engine(url, connect_args={"check_same_thread": False})
    Base.metadata.create_all(db_engine)
    factory = sessionmaker(bind=db_engine, autoflush=False, autocommit=False)

    monkeypatch.setattr("app.services.storage.database.SessionLocal", factory)
    monkeypatch.setattr("app.config.settings.storage_backend", "database")
    reset_storage_cache()

    def override_get_db():
        db = factory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    yield TestClient(app)

    app.dependency_overrides.clear()
    reset_storage_cache()
    db_engine.dispose()


def auth(client, email="subs@example.com") -> dict:
    client.post(
        "/auth/register",
        json={"email": email, "password": PASSWORD, "full_name": "Subs"},
    )
    token = client.post(
        "/auth/login", data={"username": email, "password": PASSWORD}
    ).json()["access_token"]
    return {"Authorization": f"Bearer {token}"}


def real_cues(duration: float = 12.0) -> list[dict]:
    """A track built by the shipping script-timing path, not typed by hand."""
    cues = engine.cues_from_script(SCRIPT, duration_seconds=duration)
    assert len(cues) >= 3, "the fixture script should produce several cues"
    return cues


# ===========================================================================
# 1. Cue construction
# ===========================================================================


def test_a_script_is_timed_into_readable_cues():
    cues = real_cues(duration=12.0)

    assert engine.total_duration(cues) == pytest.approx(12.0, abs=0.01)
    # Every cue is inside the reading limits the style asks for.
    for cue in cues:
        assert cue["end"] > cue["start"]
        for line in cue["text"].split("\n"):
            assert len(line) <= engine.DEFAULT_MAX_CHARS_PER_LINE
        assert len(cue["text"].split("\n")) <= engine.DEFAULT_MAX_LINES


def test_script_timing_apportions_by_length_not_evenly():
    """"OK." and a 30-word clause are not the same length of speech."""
    cues = engine.cues_from_script(
        "Hi. " + ("A rather much longer sentence that keeps going for a while. "),
        duration_seconds=10,
    )
    assert len(cues) >= 2
    first = cues[0]["end"] - cues[0]["start"]
    second = cues[1]["end"] - cues[1]["start"]
    assert second > first


def test_a_transcript_becomes_cues_split_on_reading_limits(provider):
    """A speech model returns whatever segment length it felt like; that is not
    a subtitle. This is the step that makes it one."""
    import asyncio

    transcript = asyncio.run(
        provider.transcribe(audio=b"x", filename="a.wav", content_type="audio/wav")
    )
    cues = engine.cues_from_transcript(transcript)

    assert len(cues) >= len(transcript.segments)
    for cue in cues:
        for line in cue["text"].split("\n"):
            assert len(line) <= engine.DEFAULT_MAX_CHARS_PER_LINE


def test_normalize_removes_overlaps_and_orders_the_track():
    messy = [
        {"start": 5.0, "end": 7.0, "text": "second"},
        {"start": 0.0, "end": 6.0, "text": "first, overlapping"},
    ]

    cleaned = engine.normalize(messy)

    assert [c["text"] for c in cleaned] == ["first, overlapping", "second"]
    assert cleaned[0]["end"] <= cleaned[1]["start"]


# ===========================================================================
# 2. Editing
# ===========================================================================


def test_split_then_merge_returns_the_original_track():
    """The strongest statement the two operations can make about each other."""
    cues = real_cues()

    split = engine.split_cue(cues, 1)
    assert len(split) == len(cues) + 1

    merged = engine.merge_cues(split, [1, 2])

    assert len(merged) == len(cues)
    assert [c["text"] for c in merged] == [c["text"] for c in cues]
    assert merged[1]["start"] == pytest.approx(cues[1]["start"], abs=0.01)
    assert merged[1]["end"] == pytest.approx(cues[1]["end"], abs=0.01)


def test_a_split_never_cuts_a_word_in_half():
    cues = real_cues()
    original = cues[1]["text"]

    split = engine.split_cue(cues, 1, at_character=len(original) // 2)

    head, tail = split[1]["text"], split[2]["text"]
    # Every word survives intact across the two halves.
    assert head.split() + tail.split() == original.split()


def test_a_split_hands_the_seam_to_both_halves():
    cues = real_cues()
    split = engine.split_cue(cues, 1, at_seconds=cues[1]["start"] + 1.0)

    assert split[1]["start"] == pytest.approx(cues[1]["start"], abs=0.01)
    assert split[2]["end"] == pytest.approx(cues[1]["end"], abs=0.01)
    assert split[1]["end"] <= split[2]["start"]


def test_a_one_word_cue_cannot_be_split():
    cues = engine.normalize([{"start": 0.0, "end": 3.0, "text": "Hello"}])
    with pytest.raises(engine.SubtitleEditError, match="one word"):
        engine.split_cue(cues, 0)


def test_only_adjacent_cues_can_be_merged():
    cues = real_cues()
    with pytest.raises(engine.SubtitleEditError, match="next to each other"):
        engine.merge_cues(cues, [0, 2])


def test_merging_keeps_the_words_over_their_own_audio():
    cues = real_cues()
    merged = engine.merge_cues(cues, [0, 1])

    assert merged[0]["start"] == pytest.approx(cues[0]["start"], abs=0.01)
    assert merged[0]["end"] == pytest.approx(cues[1]["end"], abs=0.01)


def test_inserting_lands_in_the_position_asked_for():
    """A contiguous track has no gap, so the insert has to make room — and if
    it silently reordered instead, this is what would catch it."""
    cues = real_cues()

    added = engine.insert_cue(cues, index=0, text="Inserted line")

    assert added[1]["text"] == "Inserted line"
    assert added[0]["text"] == cues[0]["text"]
    assert added[1]["start"] >= added[0]["end"]
    assert added[2]["start"] >= added[1]["end"]


def test_inserting_is_refused_when_there_is_genuinely_no_room():
    tight = engine.normalize(
        [{"start": 0.0, "end": 1.0, "text": "one"}, {"start": 1.05, "end": 1.7, "text": "two"}]
    )
    with pytest.raises(engine.SubtitleEditError, match="no room"):
        engine.insert_cue(tight, index=0, text="squeeze")


def test_deleting_leaves_the_other_timings_alone():
    cues = real_cues()
    remaining = engine.delete_cue(cues, 1)

    assert len(remaining) == len(cues) - 1
    assert remaining[0] == cues[0]


def test_a_cue_cannot_be_emptied_by_editing():
    cues = real_cues()
    with pytest.raises(engine.SubtitleEditError, match="needs some text"):
        engine.update_cue(cues, 0, text="   ")


def test_search_replace_reports_its_count_and_leaves_timing_alone():
    """The count is the only way to tell a working find from a silent
    no-match, and re-timing would break the one job this exists for."""
    cues = real_cues()

    replaced, count = engine.search_replace(cues, find="Autumn", replace="Winter")

    assert count == 1
    assert "Winter" in replaced[0]["text"]
    assert [(c["start"], c["end"]) for c in replaced] == [(c["start"], c["end"]) for c in cues]


def test_search_replace_is_case_insensitive_by_default():
    cues = real_cues()
    _, count = engine.search_replace(cues, find="autumn", replace="Winter")
    assert count == 1

    _, strict = engine.search_replace(cues, find="autumn", replace="W", case_sensitive=True)
    assert strict == 0


def test_whole_word_replace_does_not_match_inside_a_word():
    cues = engine.cues_from_script("We are open. Openness matters.", duration_seconds=6)

    _, loose = engine.search_replace(cues, find="open", replace="shut")
    _, exact = engine.search_replace(cues, find="open", replace="shut", whole_word=True)

    assert loose > exact
    assert exact == 1


def test_shifting_moves_the_whole_track_and_clamps_at_zero():
    cues = real_cues()

    later = engine.shift(cues, 5.0)
    assert later[0]["start"] == pytest.approx(cues[0]["start"] + 5.0, abs=0.01)

    earlier = engine.shift(cues, -1000.0)
    assert earlier[0]["start"] == 0.0


# ===========================================================================
# 3. Styling
# ===========================================================================


def test_a_style_is_validated_rather_than_trusted():
    """A position of "diagonal" is not a style, it is a track the renderer
    cannot draw."""
    cleaned = engine.clean_style(
        {"position": "diagonal", "align": "sideways", "animation": "explode",
         "font_size": 9000, "max_lines": 40, "font_family": "Comic Papyrus"}
    )

    assert cleaned["position"] in engine.SUBTITLE_POSITIONS
    assert cleaned["align"] in engine.SUBTITLE_ALIGNMENTS
    assert cleaned["animation"] in engine.SUBTITLE_ANIMATIONS
    assert cleaned["font_family"] in engine.SUBTITLE_FONTS
    assert cleaned["font_size"] <= 200
    assert cleaned["max_lines"] <= 4


def test_a_partial_style_is_filled_in_not_left_broken():
    """A style from an older build must still render."""
    cleaned = engine.clean_style({"color": "#FF0000"})

    assert cleaned["color"] == "#FF0000"
    assert cleaned["font_family"] and cleaned["position"] and cleaned["font_size"]


def test_every_preset_survives_validation_unchanged():
    """A preset that its own validator would rewrite is a preset that lies."""
    for key in engine.SUBTITLE_PRESETS:
        style = engine.preset(key)
        cleaned = engine.clean_style(style)
        for field in ("position", "align", "animation", "font_family", "font_size", "max_lines"):
            assert cleaned[field] == style[field], f"{key}.{field}"


# ===========================================================================
# 4. Export
# ===========================================================================


def test_srt_round_trips_through_the_parser():
    cues = real_cues()

    srt, content_type, extension = transcription_service.render(cues, "srt")
    reparsed = engine.parse(srt)

    assert (content_type, extension) == ("application/x-subrip", "srt")
    assert len(reparsed) == len(cues)
    for original, parsed in zip(cues, reparsed):
        assert parsed["text"] == original["text"]
        assert parsed["start"] == pytest.approx(original["start"], abs=0.01)
        assert parsed["end"] == pytest.approx(original["end"], abs=0.01)


def test_vtt_round_trips_and_carries_its_header():
    cues = real_cues()

    vtt, content_type, _ = transcription_service.render(cues, "vtt")

    assert vtt.startswith("WEBVTT")
    assert content_type == "text/vtt"
    # WebVTT uses a dot before the milliseconds; SRT uses a comma. Getting this
    # wrong produces a file players silently ignore.
    assert "." in vtt.split("-->")[0].split("\n")[-1]
    assert len(engine.parse(vtt)) == len(cues)


def test_txt_is_the_words_with_no_timings():
    cues = real_cues()

    txt, content_type, _ = transcription_service.render(cues, "txt")

    assert content_type == "text/plain"
    assert "-->" not in txt
    for cue in cues:
        assert cue["text"].replace("\n", " ") in txt.replace("\n", " ")


def test_exporting_an_empty_track_is_refused():
    with pytest.raises(transcription_service.TranscriptionError, match="no subtitles"):
        transcription_service.render([], "srt")


def test_an_unknown_format_is_refused():
    with pytest.raises(transcription_service.TranscriptionError):
        transcription_service.render(real_cues(), "ass")


# ===========================================================================
# 5. Transcription pipeline
# ===========================================================================


def test_audio_is_extracted_from_video_before_transcription(real_mp4, provider):
    """A 200 MB screen recording cannot be posted to a speech API, and 199 MB
    of it is pixels the model never looks at."""
    audio, content_type, filename = transcription_service.prepare_audio(
        real_mp4, content_type="video/mp4", filename="screen.mp4"
    )

    assert content_type == "audio/mpeg"
    assert filename.endswith(".mp3")
    assert len(audio) < len(real_mp4)
    assert audio[:2] in (b"\xff\xfb", b"\xff\xf3", b"\xff\xf2", b"ID")


def test_small_audio_is_passed_through_untouched(real_wav):
    same, content_type, filename = transcription_service.prepare_audio(
        real_wav, content_type="audio/wav", filename="clip.wav"
    )

    assert same is real_wav
    assert (content_type, filename) == ("audio/wav", "clip.wav")


def test_transcribe_end_to_end_stores_the_source_and_meters(client, real_wav, provider):
    from app.models.usage_event import UsageEvent

    headers = auth(client)

    response = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("clip.wav", real_wav, "audio/wav")},
        data={"language": "en"},
    )

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["provider"] == "fake-whisper"
    assert body["language"] == "English"
    assert len(body["cues"]) >= 3
    assert body["word_count"] == 2
    # The upload is kept so the editor can play it back while timing is checked.
    assert body["source_asset_id"] is not None
    assert "/api/storage/o/" in body["source_url"]
    # The provider got the language hint, as a bare ISO code.
    assert provider.calls[-1]["language"] == "en"

    db = next(app.dependency_overrides[get_db]())
    metered = db.query(UsageEvent).filter_by(metric="transcription_seconds").all()
    stored = db.query(VideoAsset).count()
    db.close()
    assert [e.quantity for e in metered] == [9.5]
    assert stored == 1


def test_a_video_upload_is_reduced_before_it_reaches_the_provider(client, real_mp4, provider):
    headers = auth(client)

    response = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("clip.mp4", real_mp4, "video/mp4")},
    )

    assert response.status_code == 200, response.text
    # The provider was handed audio, not the container.
    assert provider.calls[-1]["content_type"] == "audio/mpeg"
    assert provider.calls[-1]["bytes"] < len(real_mp4)


def test_a_file_with_no_audio_track_is_refused(client, provider):
    """Refused before anything is uploaded to a vendor."""
    headers = auth(client)
    png = bytes.fromhex(
        "89504e470d0a1a0a0000000d494844520000000100000001080600000"
        "01f15c4890000000a49444154789c6360000002000100ffff03000006"
        "000557bfabd40000000049454e44ae426082"
    )

    response = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("picture.png", png, "image/png")},
    )

    assert response.status_code == 422
    assert provider.calls == []


def test_transcription_can_skip_storing_the_source(client, real_wav, provider):
    headers = auth(client)

    body = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("clip.wav", real_wav, "audio/wav")},
        data={"store_source": "false"},
    ).json()

    assert body["source_asset_id"] is None
    db = next(app.dependency_overrides[get_db]())
    count = db.query(VideoAsset).count()
    db.close()
    assert count == 0


def test_a_recording_and_its_script_together_give_audio_timing_and_script_wording(
    client, real_wav, provider
):
    """The combined workflow, end to end over the real routes.

    Upload a real audio file, transcribe it through the real pipeline, then
    correct the result against the script the speaker was reading from. The
    thing being asserted is the division of labour: every timestamp comes from
    the audio, and only the *spelling* comes from the document.
    """
    headers = auth(client, email="combined@example.com")

    transcribed = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("talk.wav", real_wav, "audio/wav")},
    ).json()

    # The script as it was written: same words, one of which the model would
    # plausibly mishear, plus a sentence the speaker never got to.
    script = (
        "Autumn is here, and so is our new seasonal menu. "
        "Come in for spiced apple cake and a flat white. "
        "We are open until six every day this week. "
        "Bring a friend and the second coffee is on us."
    )

    aligned = client.post(
        "/api/video/subtitles/align",
        headers=headers,
        json={"cues": transcribed["cues"], "script": script},
    )

    assert aligned.status_code == 200
    body = aligned.json()
    assert body["alignment"]["applied"] is True

    # Timing is the audio's, to the millisecond.
    assert body["duration_seconds"] == pytest.approx(
        transcribed["duration_seconds"] and engine.total_duration(transcribed["cues"]),
        abs=0.001,
    )
    assert body["cues"][0]["start"] == transcribed["cues"][0]["start"]

    # The sentence that was never spoken is not in the subtitles, because there
    # is no audio under it to put it over.
    text = " ".join(" ".join(cue["text"].split()) for cue in body["cues"])
    assert "second coffee" not in text
    assert body["alignment"]["skipped_words"] >= 8


def test_a_script_is_optional_and_transcription_alone_still_works(
    client, real_wav, provider
):
    """The rule: at least one input, and everything else is optional.

    A recording with no script must never be refused for not having one, and
    the cues it produces must be complete on their own.
    """
    headers = auth(client, email="alone@example.com")

    response = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("talk.wav", real_wav, "audio/wav")},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["cues"], "a recording on its own has to produce a track"
    assert "alignment" not in body, "no script was given, so there is nothing to report"


def test_a_provider_failure_is_502_and_a_config_error_is_503(client, real_wav, provider):
    """A provider fault is 502, not 422.

    This route used to answer 422 — "unprocessable request" — when the speech
    service failed, while `/api/ads/*` answered 502 for the same outage. The
    caller had typed nothing wrong, so 422 pointed them at their own input.
    `app.api_errors` decides it now, and the detail is no longer echoed back.
    """
    headers = auth(client)

    provider.fail_with = MediaProviderError("the speech service is rate limiting")
    failed = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("clip.wav", real_wav, "audio/wav")},
    )
    assert failed.status_code == 502
    assert failed.headers.get("X-Error-Code") == "provider_unavailable"
    # The upstream wording stays in the log, not in the response.
    assert "rate limiting" not in failed.json()["detail"]

    provider.fail_with = MediaProviderConfigError("GROQ_API_KEY is not set.")
    unconfigured = client.post(
        "/api/video/subtitles/transcribe",
        headers=headers,
        files={"file": ("clip.wav", real_wav, "audio/wav")},
    )
    assert unconfigured.status_code == 503
    # A config error is our own message, so the missing key is still named —
    # that is the one detail an operator needs.
    assert "GROQ_API_KEY" in unconfigured.json()["detail"]


# ===========================================================================
# 6. Routes
# ===========================================================================


@pytest.mark.parametrize(
    ("method", "path"),
    [
        ("get", "/api/video/subtitles/styles"),
        ("get", "/api/video/subtitles/formats"),
        ("post", "/api/video/subtitles/transcribe"),
        ("post", "/api/video/subtitles/from-script"),
        ("post", "/api/video/subtitles/from-document"),
        ("post", "/api/video/subtitles/align"),
        ("post", "/api/video/subtitles/edit/split"),
        ("post", "/api/video/subtitles/export"),
        ("get", "/api/video/subtitles/files"),
        ("post", "/api/video/subtitles/attach"),
        ("get", "/api/video/subtitles/tracks?project_id=1"),
    ],
)
def test_every_subtitle_route_requires_a_token(client, method, path):
    kwargs = {"json": {}} if method == "post" else {}
    assert getattr(client, method)(path, **kwargs).status_code == 401


def test_styles_serves_the_presets_and_the_vocabularies(client):
    headers = auth(client)

    body = client.get("/api/video/subtitles/styles", headers=headers).json()

    assert {p["key"] for p in body["presets"]} == set(engine.SUBTITLE_PRESETS)
    assert body["default_preset"] == engine.DEFAULT_PRESET
    # Served rather than hardcoded in the frontend, because the renderer has to
    # understand every value the editor can produce.
    assert set(body["animations"]) == set(engine.SUBTITLE_ANIMATIONS)
    assert set(body["positions"]) == set(engine.SUBTITLE_POSITIONS)


def test_from_script_flags_estimated_timing(client):
    headers = auth(client)

    estimated = client.post(
        "/api/video/subtitles/from-script", headers=headers, json={"text": SCRIPT}
    ).json()
    fitted = client.post(
        "/api/video/subtitles/from-script",
        headers=headers,
        json={"text": SCRIPT, "duration_seconds": 15},
    ).json()

    # With no audio behind it the timing is a guess, and the API says so.
    assert estimated["estimated"] is True
    assert fitted["estimated"] is False
    assert fitted["duration_seconds"] == pytest.approx(15.0, abs=0.01)


def test_editing_routes_apply_the_engine_rules(client):
    headers = auth(client)
    cues = real_cues()

    split = client.post(
        "/api/video/subtitles/edit/split", headers=headers, json={"cues": cues, "index": 1}
    ).json()
    assert split["cue_count"] == len(cues) + 1

    merged = client.post(
        "/api/video/subtitles/edit/merge",
        headers=headers,
        json={"cues": split["cues"], "indices": [1, 2]},
    ).json()
    assert merged["cue_count"] == len(cues)

    replaced = client.post(
        "/api/video/subtitles/edit/search-replace",
        headers=headers,
        json={"cues": cues, "find": "Autumn", "replace": "Winter"},
    ).json()
    assert replaced["replacements"] == 1


def test_a_refused_edit_is_422_with_the_reason(client):
    headers = auth(client)
    cues = real_cues()

    response = client.post(
        "/api/video/subtitles/edit/merge",
        headers=headers,
        json={"cues": cues, "indices": [0, 2]},
    )

    assert response.status_code == 422
    assert "next to each other" in response.json()["detail"]


def test_importing_an_srt_file_reopens_it_for_editing(client):
    headers = auth(client)
    cues = real_cues()
    srt, _, _ = transcription_service.render(cues, "srt")

    body = client.post(
        "/api/video/subtitles/import",
        headers=headers,
        files={"file": ("existing.srt", srt.encode("utf-8"), "application/x-subrip")},
    ).json()

    assert body["cue_count"] == len(cues)
    assert body["cues"][0]["text"] == cues[0]["text"]


def test_importing_something_that_is_not_subtitles_is_refused(client):
    headers = auth(client)

    response = client.post(
        "/api/video/subtitles/import",
        headers=headers,
        files={"file": ("notes.txt", b"just some prose with no timings", "text/plain")},
    )

    assert response.status_code == 422


# ===========================================================================
# 7. Export storage
# ===========================================================================


def test_exporting_writes_the_file_to_object_storage(client):
    """A subtitle file is small, but "small files may go in the database" is
    the exception that grows until the rule is meaningless."""
    headers = auth(client)
    cues = real_cues()

    stored = client.post(
        "/api/video/subtitles/export",
        headers=headers,
        json={"cues": cues, "format": "srt", "title": "Autumn menu"},
    )

    assert stored.status_code == 201
    body = stored.json()
    assert body["format"] == "srt"
    assert body["cue_count"] == len(cues)
    assert "/api/storage/o/" in body["url"]

    db = next(app.dependency_overrides[get_db]())
    asset = db.query(VideoAsset).filter_by(kind="subtitle").one()
    obj = db.query(StorageObject).filter_by(key=asset.storage_key).one()
    db.close()

    # The row keeps a key; the bytes are in the store.
    assert asset.storage_key.endswith(".srt")
    assert obj.data.decode("utf-8").startswith("1\n")


def test_a_stored_export_downloads_in_any_of_the_three_formats(client):
    """Three views of one track, not three files to keep in step."""
    headers = auth(client)
    cues = real_cues()

    stored = client.post(
        "/api/video/subtitles/export",
        headers=headers,
        json={"cues": cues, "format": "srt", "title": "Menu"},
    ).json()

    srt = client.get(f"/api/video/subtitles/files/{stored['id']}/download?format=srt", headers=headers)
    vtt = client.get(f"/api/video/subtitles/files/{stored['id']}/download?format=vtt", headers=headers)
    txt = client.get(f"/api/video/subtitles/files/{stored['id']}/download?format=txt", headers=headers)

    assert srt.content.decode().startswith("1\n")
    assert vtt.content.decode().startswith("WEBVTT")
    assert "-->" not in txt.content.decode()
    assert "Menu.vtt" in vtt.headers["content-disposition"]


def test_exports_are_listed_and_scoped_to_their_owner(client):
    mine = auth(client, "mine@example.com")
    theirs = auth(client, "theirs@example.com")
    cues = real_cues()

    client.post("/api/video/subtitles/export", headers=mine, json={"cues": cues, "format": "srt"})
    client.post("/api/video/subtitles/export", headers=theirs, json={"cues": cues, "format": "vtt"})

    listed = client.get("/api/video/subtitles/files", headers=mine).json()

    assert len(listed) == 1
    assert listed[0]["format"] == "srt"


def test_another_accounts_export_cannot_be_downloaded_or_deleted(client):
    mine = auth(client, "one@example.com")
    theirs = auth(client, "two@example.com")

    stored = client.post(
        "/api/video/subtitles/export", headers=theirs, json={"cues": real_cues(), "format": "srt"}
    ).json()

    assert client.get(
        f"/api/video/subtitles/files/{stored['id']}/download", headers=mine
    ).status_code == 404
    assert client.delete(
        f"/api/video/subtitles/files/{stored['id']}", headers=mine
    ).status_code == 404


def test_deleting_an_export_removes_its_object(client):
    headers = auth(client)
    stored = client.post(
        "/api/video/subtitles/export", headers=headers, json={"cues": real_cues(), "format": "srt"}
    ).json()

    assert client.delete(f"/api/video/subtitles/files/{stored['id']}", headers=headers).status_code == 204

    db = next(app.dependency_overrides[get_db]())
    counts = (db.query(VideoAsset).count(), db.query(StorageObject).count())
    db.close()
    assert counts == (0, 0)


# ===========================================================================
# 8. Add to project
# ===========================================================================


def test_subtitles_can_be_added_to_a_project_made_separately(client):
    headers = auth(client)
    cues = real_cues()
    project = client.post("/api/video/projects", headers=headers, json={}).json()

    track = client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={
            "cues": cues,
            "project_id": project["id"],
            "language": "en",
            "style": {"position": "top", "font_size": 60},
        },
    )

    assert track.status_code == 200
    body = track.json()
    assert body["cue_count"] == len(cues)
    assert body["is_primary"] is True
    assert body["style"]["position"] == "top"
    assert body["style"]["font_size"] == 60
    # A project's duration counts its subtitles even with an empty timeline.
    reloaded = client.get(f"/api/video/projects/{project['id']}", headers=headers).json()
    assert reloaded["duration_seconds"] == pytest.approx(engine.total_duration(cues), abs=0.01)


def test_attaching_fills_the_projects_empty_track_rather_than_adding_a_second(client):
    """Every project is created with one empty subtitle track. Filling it in is
    what "add subtitles" means — leaving an empty one beside a full one is not."""
    headers = auth(client)
    project = client.post("/api/video/projects", headers=headers, json={}).json()
    assert project["subtitle_count"] == 1

    client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={"cues": real_cues(), "project_id": project["id"], "language": "en-US"},
    )

    tracks = client.get(
        f"/api/video/subtitles/tracks?project_id={project['id']}", headers=headers
    ).json()
    assert len(tracks) == 1
    assert tracks[0]["cue_count"] > 0


def test_re_attaching_the_same_track_replaces_it(client):
    headers = auth(client)
    project = client.post("/api/video/projects", headers=headers, json={}).json()

    first = client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={"cues": real_cues(), "project_id": project["id"], "language": "en"},
    ).json()

    edited = engine.delete_cue(real_cues(), 0)
    again = client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={
            "cues": edited,
            "project_id": project["id"],
            "language": "en",
            "track_id": first["id"],
        },
    ).json()

    assert again["id"] == first["id"]
    assert again["cue_count"] == len(edited)

    tracks = client.get(
        f"/api/video/subtitles/tracks?project_id={project['id']}", headers=headers
    ).json()
    assert len(tracks) == 1


def test_a_second_language_becomes_its_own_track(client):
    headers = auth(client)
    project = client.post("/api/video/projects", headers=headers, json={}).json()

    for language in ("en", "ur"):
        client.post(
            "/api/video/subtitles/attach",
            headers=headers,
            json={"cues": real_cues(), "project_id": project["id"], "language": language},
        )

    tracks = client.get(
        f"/api/video/subtitles/tracks?project_id={project['id']}", headers=headers
    ).json()

    assert {t["language"] for t in tracks} == {"en", "ur"}
    # Exactly one primary — it is the track that gets burned in.
    assert sum(1 for t in tracks if t["is_primary"]) == 1


def test_subtitles_cannot_be_written_into_another_accounts_project(client):
    mine = auth(client, "a@example.com")
    theirs = auth(client, "b@example.com")
    their_project = client.post("/api/video/projects", headers=theirs, json={}).json()

    response = client.post(
        "/api/video/subtitles/attach",
        headers=mine,
        json={"cues": real_cues(), "project_id": their_project["id"], "language": "en"},
    )

    assert response.status_code == 404
    assert client.get(
        f"/api/video/subtitles/tracks?project_id={their_project['id']}", headers=mine
    ).status_code == 404


def test_attaching_an_empty_track_is_refused(client):
    headers = auth(client)
    project = client.post("/api/video/projects", headers=headers, json={}).json()

    response = client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={"cues": [], "project_id": project["id"], "language": "en"},
    )

    assert response.status_code == 422


def test_a_bad_style_is_cleaned_before_it_reaches_the_project(client):
    headers = auth(client)
    project = client.post("/api/video/projects", headers=headers, json={}).json()

    track = client.post(
        "/api/video/subtitles/attach",
        headers=headers,
        json={
            "cues": real_cues(),
            "project_id": project["id"],
            "language": "en",
            "style": {"position": "diagonal", "font_size": 9999},
        },
    ).json()

    assert track["style"]["position"] in engine.SUBTITLE_POSITIONS
    assert track["style"]["font_size"] <= 200
