"""Request and response shapes for AI video creation.

One rule shapes this whole file: **everything generated comes back as an
editable document, and every one of those documents can be sent straight back
to be saved.** The script the model wrote and the script the user edits are the
same shape on the same endpoint; so are the scenes. There is no "generated"
representation that has to be converted before a human can touch it.

That is why there is a `ScriptDocument` with a PUT as well as a generate, and a
`SceneUpdate` alongside the batch generator. A pipeline whose output could only
be regenerated, never amended, is the "separate uneditable output" this feature
is specifically not allowed to be.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.services.video import scripting


# ---------------------------------------------------------------------------
# Options
# ---------------------------------------------------------------------------


class AIOptions(BaseModel):
    """Everything the "new AI video" form needs to build itself.

    Served rather than duplicated in JavaScript, the same rule the subtitle
    style panel follows: the generator has to understand every value the form
    can produce.
    """

    tones: list[str]
    content_types: list[str]
    visual_modes: list[str]
    languages: list[dict]
    duration_range: list[int]
    # The lengths offered as one tap. `duration_range` is what is accepted.
    durations: list[int] = Field(default_factory=list)
    default_duration: int
    # The longest video this deployment will render, and the longest script it
    # will cut into a project. A script may be longer than either — Script
    # Studio writes scripts, which is not the same as rendering them.
    max_video_seconds: int = 0
    project_max_seconds: int = 0
    platforms: list[dict] = Field(default_factory=list)
    # False when no text provider is configured — the UI says so instead of
    # offering a generate button that will always fail.
    text_available: bool = True


# ---------------------------------------------------------------------------
# Script
# ---------------------------------------------------------------------------


class ScriptBrief(BaseModel):
    """The eight inputs the script is written from."""

    topic: str = Field(min_length=3, max_length=300)
    language: str = "en-US"
    tone: str = "friendly"
    audience: str = Field(default="a general audience", max_length=200)
    duration_seconds: float = Field(default=30, ge=5, le=1800)
    platform: str = "youtube_shorts"
    content_type: str = "educational"
    instructions: str | None = Field(default=None, max_length=1000)
    visual_mode: Literal["natural", "animated"] = "natural"


class ScriptPoint(BaseModel):
    id: str = ""
    heading: str = ""
    text: str = ""


class ScriptDocument(BaseModel):
    """A script — the same shape whether a model wrote it or a person did.

    `estimated_seconds` and `fits_budget` are computed from the words actually
    in it, so they update as the user edits rather than reporting what the
    generator was aiming for.
    """

    version: int = 1
    brief: dict = Field(default_factory=dict)
    title: str = ""
    hook: str = ""
    introduction: str = ""
    main_points: list[ScriptPoint] = Field(default_factory=list)
    ending: str = ""
    cta: str = ""
    keywords: list[str] = Field(default_factory=list)
    estimated_seconds: float = 0.0
    fits_budget: bool = True
    generated_at: str | None = None


class ScriptSectionRewrite(BaseModel):
    """Rewrite one part of a script, leaving the rest of it alone.

    The whole document goes in and the whole document comes back, so the client
    replaces its state in one move and the recomputed duration arrives with the
    new text rather than needing a second call.

    `brief` is optional because a script generated by this API already carries
    the brief it was written from; it is only needed for a script that arrived
    from somewhere else.
    """

    script: dict
    section: Literal["title", "hook", "introduction", "ending", "cta", "point"]
    # Which main point, when section is "point".
    point_id: str = Field(default="", max_length=40)
    brief: ScriptBrief | None = None


class ScriptSave(BaseModel):
    """Save an edited script. The whole document, not a patch.

    A script is five short strings; sending all of them costs nothing and
    avoids a class of merge problem where a field the client did not know about
    is silently dropped.
    """

    script: dict
    expected_revision: int | None = None


# ---------------------------------------------------------------------------
# Scenes
# ---------------------------------------------------------------------------


class SceneRead(BaseModel):
    """One scene of the storyboard, with everything Task 7 asks a scene to
    carry: what is said, how long for, what should be on screen, what kind of
    visual it is, how it hands over, and the words drawn over it."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    position: int
    title: str | None = None
    # The narration — what the voice reads and the subtitles are built from.
    text: str | None = None
    # What should be on screen, in words.
    visual_prompt: str | None = None
    # pending | ai_image | stock | upload | color | asset
    source: str
    asset_id: int | None = None
    asset_url: str | None = None
    voice_asset_id: int | None = None
    voice_url: str | None = None
    voice_duration: float | None = None
    start_seconds: float
    duration_seconds: float
    transition: str
    settings: dict = Field(default_factory=dict)


class SceneUpdate(BaseModel):
    """Edit one scene. Every field optional — the inspector sends what changed.

    `asset_id` is settable so "use this file instead" is the same operation as
    everything else, rather than a separate replace endpoint.
    """

    title: str | None = Field(default=None, max_length=200)
    text: str | None = None
    visual_prompt: str | None = None
    source: str | None = None
    asset_id: int | None = None
    voice_asset_id: int | None = None
    duration_seconds: float | None = Field(default=None, ge=0.5, le=30)
    transition: str | None = None
    overlay_text: str | None = None


class SceneReorder(BaseModel):
    scene_ids: list[int]


class StoryboardRead(BaseModel):
    project_id: int
    scenes: list[SceneRead]
    summary: dict
    script: dict = Field(default_factory=dict)


class GenerateScenes(BaseModel):
    """Rebuild the storyboard from the project's script.

    `describe_visuals` is opt-out because it costs a model call; a user
    re-cutting the same script into scenes after an edit does not need new
    visual prompts.
    """

    total_seconds: float | None = Field(default=None, ge=5, le=600)
    describe_visuals: bool = True


# ---------------------------------------------------------------------------
# Per-scene generation
# ---------------------------------------------------------------------------


class VisualRequest(BaseModel):
    """Give one scene a picture.

    `strategy` forces a source — the "try an AI image instead" button. Left
    out, the scene's visual mode decides the chain (see
    `visuals.MODE_STRATEGIES`).
    """

    strategy: Literal["stock", "ai_image", "color"] | None = None
    prompt: str | None = Field(default=None, max_length=500)


class VoiceRequest(BaseModel):
    """Narrate one scene, or the whole storyboard."""

    voice_id: str | None = None
    style: str | None = None
    rate: float = Field(default=1.0, ge=0.5, le=2.0)
    pitch: float = Field(default=1.0, ge=0.5, le=2.0)
    volume: float = Field(default=1.0, ge=0.1, le=2.0)


class SubtitleRequest(BaseModel):
    """Build a subtitle track from the scenes.

    Timed from each scene's real start and duration rather than from a reading
    estimate over the whole script — the storyboard already knows when every
    line is spoken, so guessing would be throwing information away.
    """

    style: str | None = None
    language: str | None = None


class BuildRequest(BaseModel):
    """Assemble the scenes into the project's timeline."""

    include_voice: bool = True
    include_text: bool = True


# ---------------------------------------------------------------------------
# The whole pipeline
# ---------------------------------------------------------------------------


class CreateAIProject(ScriptBrief):
    """Create a project and write its script and storyboard in one call.

    Deliberately stops at the storyboard. Visuals and voice are per-scene calls
    the client makes with a progress bar, because generating eight images
    inside one request is a request that times out — and a user watching
    "5 of 8 visuals" is being told the truth in a way a spinner is not.
    """

    # A project is a video in the making, so its length is bounded by what the
    # video pipeline can carry — a scene, a visual and a voice-over per beat.
    # `ScriptBrief` itself goes much further (Script Studio writes half-hour
    # scripts), which is why this is narrowed here rather than there.
    duration_seconds: float = Field(
        default=30, ge=5, le=scripting.MAX_PROJECT_SECONDS
    )

    name: str | None = Field(default=None, max_length=200)
    # A script the user already wrote and edited — in Script Studio, say.
    # Sent here it is used as-is; leaving it out writes a fresh one from the
    # brief. Without this, taking a script into a project would regenerate it
    # and discard every edit that made the user want to keep it.
    script: dict | None = None


class AIProjectCreated(BaseModel):
    project_id: int
    project: dict
    script: dict
    scenes: list[SceneRead]
    summary: dict
    # What the client should do next, in order. Sent by the server so the
    # sequence lives with the pipeline rather than being hardcoded in the UI.
    next_steps: list[str] = Field(default_factory=list)
