import { useState } from 'react'
import AdsWorkspace, { Field, RailSection } from '../../../components/ads/workspace/AdsWorkspace.jsx'
import GenerateButton from '../../../components/ads/workspace/GenerateButton.jsx'
import PreviewStage from '../../../components/ads/workspace/PreviewStage.jsx'
import UploadField from '../../../components/ads/workspace/UploadField.jsx'
import ChipSelect from '../../../components/ChipSelect.jsx'
import useVideoRender from '../../../hooks/useVideoRender'
import { useToast } from '../../../context/ToastContext.jsx'
import {
  ANIMATION_STYLES,
  CAMERA_MOTIONS,
  VIDEO_DURATIONS,
} from '../../../lib/ads/constants'
import { ASPECT_RATIOS } from '../../../lib/constants'

// ---------------------------------------------------------------------------
// Image to Video — rendered in the browser, not generated by a model.
//
// Animating a still is camera work: a zoom, a pan, a caption. That needs
// compositing, not a generative video model, so it runs on <canvas> +
// MediaRecorder (see lib/ads/videoRender.js) and produces a real downloadable
// file at no cost and with nothing leaving the machine.
//
// The trade is stated in the rail rather than hidden: the render is real time
// and silent. Both are consequences of doing this honestly in the browser.
// ---------------------------------------------------------------------------

const TOOL = 'Image to Video'
const PHASE = 2

export default function ImageToVideo() {
  const [files, setFiles] = useState([])
  const [duration, setDuration] = useState(10)
  const [motion, setMotion] = useState('Slow zoom in')
  const [style, setStyle] = useState('Smooth')
  const [ratio, setRatio] = useState('9:16')
  const [caption, setCaption] = useState('')

  const toast = useToast()
  const { render, save, rendering, progress, result, supported } = useVideoRender()

  const image = files[0] || null

  function generate() {
    if (!image) {
      toast.error('Upload an image, or pick one from the Media Library.')
      return
    }
    render({
      slides: [{ source: image, seconds: duration, caption: caption.trim() }],
      aspect: ratio,
      motion,
    })
  }

  return (
    <AdsWorkspace
      title={TOOL}
      description="Animate a still creative into a short video ad — camera movement, a caption, and a real file you can upload."
      controls={
        <>
          <Field label="Source image">
            <UploadField hint="The still you want to animate" onChange={setFiles} />
          </Field>

          <Field label="Duration" hint={`${duration}s`}>
            <select
              className="select"
              value={duration}
              onChange={(e) => setDuration(Number(e.target.value))}
              aria-label="Duration"
            >
              {VIDEO_DURATIONS.map((d) => (
                <option key={d.value} value={d.value}>
                  {d.label}
                </option>
              ))}
            </select>
          </Field>

          <Field label="Camera motion">
            <ChipSelect options={CAMERA_MOTIONS} value={motion} onChange={setMotion} />
          </Field>

          <Field label="Animation style">
            <ChipSelect options={ANIMATION_STYLES} value={style} onChange={setStyle} />
          </Field>

          <Field label="Caption" hint="Optional, burned in">
            <input
              className="input"
              value={caption}
              onChange={(e) => setCaption(e.target.value)}
              placeholder="Naturally made. Visibly better."
            />
          </Field>

          <Field label="Aspect ratio">
            <select
              className="select"
              value={ratio}
              onChange={(e) => setRatio(e.target.value)}
              aria-label="Aspect ratio"
            >
              {ASPECT_RATIOS.map((r) => (
                <option key={r.value} value={r.value}>
                  {r.label}
                </option>
              ))}
            </select>
          </Field>
        </>
      }
      action={
        <>
          <GenerateButton
            label={`Render ${duration}s Video`}
            toolName={TOOL}
            phase={PHASE}
            onClick={generate}
            loading={rendering}
            disabled={!supported}
          />
          {rendering && (
            <div className="mt-2">
              <div className="h-1.5 w-full overflow-hidden rounded-full bg-inset">
                <div
                  className="h-full rounded-full bg-accent transition-[width] duration-150"
                  style={{ width: `${Math.round(progress * 100)}%` }}
                />
              </div>
              <p className="mt-1.5 text-center text-[11px] text-muted">
                Recording in real time — {Math.round(progress * 100)}%
              </p>
            </div>
          )}
        </>
      }
      stage={
        result ? (
          <div className="card flex min-h-[320px] flex-col p-4 lg:min-h-full">
            <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2">
              <h2 className="text-sm font-semibold text-body">Your video</h2>
              <span className="text-xs text-muted">
                {ratio} · {duration}s · .{result.extension}
              </span>
            </div>

            <div className="flex flex-1 items-center justify-center">
              <video
                key={result.url}
                src={result.url}
                controls
                loop
                playsInline
                className="max-h-[420px] rounded-xl border border-line"
              />
            </div>
          </div>
        ) : (
          <PreviewStage
            hint={'An example of the result. Upload a still, choose a camera move, and press Render — your browser makes the video.'}
            art="imageVideo"
            ratio={ratio === '9:16' ? 'story' : ratio === '16:9' ? 'landscape' : 'square'}
            toolName={TOOL}
            caption={`${duration}s · ${motion}`}
          />
        )
      }
      output={
        <>
          <RailSection title="How this renders">
            <p className="text-xs leading-relaxed text-muted">
              Rendered by your browser, not by a model — free, offline, and the file never
              leaves this machine. Two consequences: recording takes as long as the video
              is, and there is no audio track.
            </p>
          </RailSection>

          <RailSection title="Actions">
            <div className="space-y-2">
              <button
                type="button"
                onClick={() => save('image-to-video')}
                disabled={!result}
                className="btn btn-primary btn-sm w-full"
              >
                Download {result ? `.${result.extension}` : 'video'}
              </button>
              <button
                type="button"
                onClick={generate}
                disabled={rendering || !image}
                className="btn btn-secondary btn-sm w-full"
              >
                Re-render
              </button>
            </div>
          </RailSection>

          {!supported && (
            <p className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-xs leading-relaxed text-amber-700">
              This browser cannot record video. Chrome, Edge and Firefox can.
            </p>
          )}
        </>
      }
    />
  )
}
